config/routes.rb
Actioncenter::Application.routes.draw do
  get "robots.txt", controller: :robots, action: :show, format: 'text'
  get "/heartbeat", to: "robots#heartbeat"

  # Root - Redundant - TODO - refactor
  get "welcome/index"
  root 'welcome#index'

  # EFF TOOLS (Call, Share, Petition) - External Reusable Services

  post "tools/call"
  post "tools/petition"
  post "tools/tweet"
  post "tools/email"
  post "tools/message-congress"
  get "tools/reps"
  get "tools/reps_raw"
  get "tools/social_buttons_count"

  get "smarty_streets/:action", controller: :smarty_streets
  get "petition/:id/recent_signatures", :to => "petition#recent_signatures", :format => 'json'

  # Handle notifications from Amazon SES
  post "bounce/:amazon_authorize_key", :to => "sns#bounce", :format => 'json'
  post "complaint/:amazon_authorize_key", :to => "sns#complaint", :format => 'json'

  get "ahoy/visit"

  # EFF Resources

  devise_for :users, path: '', path_names:  {sign_in:  'login',
                                             sign_out: 'logout',
                                             sign_up:  'register'},
                               controllers: {sessions: 'sessions', registrations: 'registrations'}

  devise_scope :user do
    get "/sessions/password_reset" => "sessions#password_reset"
  end

  resource :user, path: 'account', only: [:show, :edit, :update] do
    member do
      delete :clear_activity
    end
  end

  # override devise's user_root (defaults to site root)
  get 'account', to: 'users#show', as: 'user_root'

  resources :action_page, path: :action, only: [:index, :show] do
    member do
      get :embed_iframe
      get :signature_count
      get :filter
      get ':institution_id' => :show_by_institution, as: :institution
    end
    collection do
      get :embed
    end
  end

  resources :subscriptions, only: [:create, :edit]

  resources :partners, only: [:show, :edit, :update] do
    member do
      get :csv
      get :presentable_csv
      post 'users' => 'partners#add_user', as: :add_user
      delete 'users/:user_id' => 'partners#remove_user', as: :remove_user
    end
  end

  resources :congress_message_campaigns, only: :none do
    resources :congress_messages, only: [:new, :create], controller: :congress_messages
  end

  namespace :admin do

    resources :source_files, :only => [:index, :create, :destroy], :controller => 's3_uploads' do
      get :generate_key, :on => :collection
    end

    get 'mailer/:action/:id' => 'mailer#:action'

    resources :congress_message_campaigns, only: :none do
      member do
        get :date_tabulation
        get :congress_tabulation
        get "staffer_report/:bioguide_id", to: "congress_message_campaigns#staffer_report", as: :staffer_report
      end
    end

    resources :em
    resources :partners
    resources :topic_categories, :topic_sets, :topics

    resources :petitions, only: %i() do
      member do
        get :presentable_csv
        get :affiliation_csv
        delete "signatures" => "petitions#destroy_signatures", as: :signatures
      end
    end

    resources :action_pages do
      get :publish
      get :unpublish
      get :destroy
      post 'update_featured_pages', :on => :collection
      patch :preview
      get :duplicate
      get :status
      get :edit_partners

      get :events
      get :"events-table"
      get :views, to: "events#views"

      resources :petitions, only: :show

      collection do
        get :homepage
        post :homepage, to: "action_pages#update_featured_action_pages"
      end
    end

    resources :institutions, except: [:show] do
      get :upload, on: :collection
      post :import, on: :collection
    end

    resources :users, only: [:index, :update]

    get "images", to: "images#index"

    resources :events, only: [:index]

    resources :categories, only: [:index, :create, :destroy]
  end
end

app/controllers/tools_controller.rb
require "rest_client"
require "uri"
require "json"

class ToolsController < ApplicationController
  include Tooling

  before_action :set_user
  before_action :set_action_page

  # Put an invisible captcha on forms are easy to submit programmatically and
  # create email subscriptions.
  invisible_captcha only: [:email, :petition]
  before_action :create_newsletter_subscription, only: [:email, :call]
  before_action :create_partner_subscription, only: [:email, :call, :petition, :message_congress]
  after_action :deliver_thanks_message, only: [:email, :call, :petition, :message_congress]
  skip_after_action :deliver_thanks_message, if: :signature_has_errors

  # See https://github.com/EFForg/action-center-platform/wiki/Deployment-Notes#csrf-protection
  skip_before_action :verify_authenticity_token
  before_action :verify_request_origin, except: :email

  def call
    ahoy.track "Action",
      { type: "action", actionType: "call", actionPageId: params[:action_id] },
      action_page: @action_page

    @name = current_user.try :name

    if params[:update_user_data] == "yes"
      update_user_data(call_params)
    end

    CallTool.campaign_call(params[:call_campaign_id],
                           phone: params[:phone],
                           location: params[:location],
                           user_id: @user.try(:id),
                           action_id: @action_page.to_param,
                           callback_url: root_url)

    render json: {}, status: 200
  end

  # GET /tools/social_buttons_count
  def social_buttons_count
    render "application/error.html.erb", status: 500
  end

  # POST /tools/petition
  #
  # A form is posted here via ajax when a user signs a petition
  def petition
    @user ||= User.find_or_initialize_by(email: params[:signature][:email])
    @email = params[:signature][:email]
    @name = params[:signature][:first_name]
    @action_page = Petition.find(params[:signature][:petition_id]).action_page
    @signature = Signature.new(signature_params.merge(user_id: @user.id))

    if @signature.zipcode.present? && @signature.country_code.blank?
      @signature.country_code = "US"
    end

    if @signature.country_code == "US" && !Rails.application.secrets.smarty_streets_id.nil?
      if city_state = SmartyStreets.get_city_state(@signature.zipcode)
        @signature.city = city_state["city"]
        @signature.state = city_state["state"]
      end
    end

    if @signature.save
      # You will only get here if you are not logged in.  Subscribe does not show for logged in users,
      # since they are presented that option at signup.
      if params[:subscribe] == "1"
        @user.attributes = signature_params.slice(
          :email, :first_name, :last_name, :city, :state, :street_address,
          :zipcode, :country_code, :phone
        )

        @source = "action center petition :: " + @action_page.title
        @user.subscribe!(opt_in = true, source = @source)
      end

      if params[:update_user_data]
        update_user_data(signature_params)
      end

      ahoy.track "Action",
        { type: "action", actionType: "signature", actionPageId: @action_page.id },
        action_page: @action_page

      respond_to do |format|
        format.json { render json: { success: true }, status: 200 }
        format.html do
          begin
            url = URI.parse(request.referrer)
            url.query = [url.query.presence, "thankyou=1"].join("&")
            redirect_to url.to_s
          rescue
            redirect_to welcome_index_path
          end
        end
      end
    else
      render json: { errors: @signature.errors.to_json }, status: 200
    end
  end

  def tweet
    ahoy.track "Action",
      { type: "action", actionType: "tweet", actionPageId: params[:action_id] },
      action_page: @action_page
    render json: { success: true }, status: 200
  end

  def email
    unless (@user and @user.events.emails.find_by_action_page_id(params[:action_id])) or params[:dnt] == "true"
      ahoy.track "Action",
        { type: "action", actionType: "email", actionPageId: params[:action_id] },
        action_page: @action_page
    end

    if params[:service] == "copy"
      @actionPage = @action_page
      render "email_target"
    else
      redirect_to @action_page.email_campaign.service_uri(params[:service])
    end
  end

  # GET /tools/reps
  #
  # This endpoint is hit by the js for tweet actions.
  # It renders json containing html markup for presentation on the view
  def reps
    @reps = CongressMember.lookup(street: params[:street_address], zipcode: params[:zipcode])
    if @reps.present?
      update_user_data(params.slice(:street_address, :zipcode)) if params[:update_user_data] == "true"

      render json: { content: render_to_string(partial: "action_page/reps") }, status: 200
    else
      render json: { error: "No representatives found" }, status: 200
    end
  end

  # GET /tools/reps_raw
  #
  # This endpoint is hit by the js for email/congress message actions to lookup what legislators
  # should be emailed based on the input long/lat or zipcode
  def reps_raw
    @reps = CongressMember.lookup(street: params[:street_address], zipcode: params[:zipcode])
    if @reps.present?
      render json: @reps, status: 200
    else
      render json: { error: "No representatives found" }, status: 200
    end
  end

  private

  def set_user
    @user = current_user
  end

  def set_action_page
    @action_page ||= ActionPage.find_by_id(params[:action_id])
  end

  def create_newsletter_subscription
    if params[:subscribe] && EmailValidator.valid?(params[:subscription][:email])
      source = "action center #{@action_page.class.name.downcase} :: " + @action_page.title
      params[:subscription][:opt_in] = true
      params[:subscription][:source] = source
      CiviCRM::subscribe params[:subscription]
    end
  end

  def signature_has_errors
    !@signature.nil? and @signature.errors.count > 0
  end

  def partner_signup_params
    attributes = %i(first_name last_name email)
    # Partner signup params might come through the main form or a nested subscription form.
    %i(signature subscription).each do |model|
      return params.require(model).permit(*attributes) if params[model].present?
    end
    params.permit(*attributes)
  end

  def signature_params
    params.require(:signature).permit(
      :first_name, :last_name, :email, :petition_id, :user_id,
      :street_address, :city, :state, :country_code, :zipcode, :anonymous,
      affiliations_attributes: [
        :id, :institution_id, :affiliation_type_id
      ]
    )
  end

  def call_params
    params.permit(:phone, :zipcode, :street_address, :action_id, :call_campaign_id)
  end

  def email_params
    params.permit(:first_name, :last_name, :street_address, :city, :state, :zipcode)
  end
end

app/views/tools/_affiliation_signatures.html.erb
<div id='signatures' class="affiliation-signatures hidden-xs">
  <h2 class='header'><%= t :signatures -%></h2>

  <div class='content clearfix'>
    <div id='signatures-filter' class='clearfix'>
      <%= form_tag filter_action_page_path(@actionPage), method: 'get' do %>
        <div id='institution-select-container'>
          <%= collection_select nil, :institution_id, @top_institutions, :id, :name,
          { prompt: t(:filter_by_institution),
            selected: @institution ? @institution.id : "" },
          { class: 'form-control institution',
            style: 'width: 100%',
            "aria-label": t(:filter_by_institution),
            "data-institutions": @institutions.to_json(only: [:id, :name]) }
          -%>
          <% if @institution %>
            <%= link_to 'remove filter', action_page_path, class: 'pull-right small' -%>
          <% end %>
        </div>
        <%= submit_tag 'Filter', class: 'eff-button' %>
      <% end %>
    </div>

    <% if @institution %>
      <div id="institution-header">
        <h3><%= @institution.name %></h3>
        <h4><%= @institution_signature_count %> signatures</h4>
      </div>
    <% end %>

    <%= render(partial: "tools/signatures", layout: false) %>
  </div>
</div>

app/views/tools/_archived.html.erb
<div class="tool mailing-list-tool">
  <div class="tool-container">
    <div class="tool-heading">
      <h2 class="tool-title">
        This action is now archived
      </h2>
    </div>
    <div class="tool-body">
      <% if @actionPage.archived_redirect_action_page_id? && current_user.admin?-%>
        <p>Hi, Señor Administrator. This page will only be visible to users who have taken action, all other users will be redirected to <%= link_to action_page_path(@actionPage.archived_redirect_action_page_id) -%>.</p>
      <% elsif @actionPage.archived_redirect_action_page_id? -%>
        <p>Thanks for taking action! A followup action has now been posted which you can find here: <%= link_to action_page_path(@actionPage.archived_redirect_action_page_id) -%>.</p>
      <% else -%>
        <p>This action has been archived and can no longer be taken.</p>
      <% end -%>
    </div>
  </div>
</div>

app/views/tools/_container.html.erb
<div id="tools" >
  <% if @actionPage.victory? -%>
    <%= render "tools/victory"  %>
  <% elsif @actionPage.archived? -%>
    <%= render "tools/archived" if @actionPage.archived? %>
  <% else -%>
    <%= render "tools/petition" if @actionPage.enable_petition? && @actionPage.petition %>
    <%= render "tools/call" if @actionPage.enable_call? && @actionPage.call_campaign %>
    <%= render "tools/email" if @actionPage.enable_email? && @actionPage.email_campaign %>
    <%= render "tools/congress_message" if @actionPage.enable_congress_message? && @actionPage.congress_message_campaign %>
    <%= render "tools/tweet" if @actionPage.enable_tweet? && @actionPage.tweet %>
    <%= render "tools/mailing_list" if @no_tools == true %>
    <% unless @actionPage.enable_call? %>
      <div class="thank-you tool">
        <%= render "tools/thank_you" %>
      </div>
    <% end %>
  <% end -%>
</div>

app/views/tools/_email.html.erb
<div id='email-tool' class="tool">
  <div class="tool-container">
    <div class="tool-heading">
      <h2 class="tool-title">Take action</h2>
      <% if params.include?('non_us_option') and params['non_us_option'] == "petition" %>
        <h3 id="non-us-option">Not in the U.S.?</h3>
      <% end %>
    </div>

    <div class="tool-body" id="target-email">
      <h3>Send this email:</h3>

      <fieldset disabled>
        <textarea class="form-control" rows="14"><%= @email_campaign.message %></textarea>
      </fieldset>
      <%= form_tag '/tools/email', method: 'post', target: '_blank' do |f| -%>
        <input type="hidden" name="action_id" value="<%= @actionPage.id %>" />
        <input type="hidden" name="dnt" value="false" />
        <%= invisible_captcha %>

        <%= render "/tools/newsletter_signup", email: true, location: true, privacy_notice: true %>

        <%= button_tag type: 'submit',
                       name: 'service',
                       value: 'default',
                       class: 'eff-button' do -%>
          Use default mail client
        <% end %>
        <p class="small">Or send using:</p>

        <%= button_tag type: 'submit',
                       name: 'service',
                       value: 'gmail',
                       class: 'eff-button' do -%>
          <i class="icon-google"></i> Gmail
        <% end %>

        <%= button_tag type: 'submit',
                       name: 'service',
                       value: 'hotmail',
                       class: 'eff-button' do -%>
          <i class="icon-windows"></i> Outlook
        <% end %>
        <br>

        <%= button_tag type: 'submit',
                       name: 'service',
                       value: 'copy',
                       data: {
                         :'clipboard-target' => 'email_target_text',
                         :placement => 'bottom',
                         :toggle => 'tooltip',
                         :title => 'Copied!',
                         :trigger => 'click',
                       },
                       id: 'copy-email-action',
                       class: 'eff-button' do -%>
          <i class="icon-copy"></i> Copy to Clipboard
        <% end %>

        <div id='email_target_text'><%= render 'tools/email_target_text' %></div>
      <% end %>
    </div>
  </div>
</div>

<div class="update-user-data-container" style="display: none;">
  <% if current_user %>
    <input checked="checked" id="update_user_data" name="update_user_data" type="checkbox" value="yes">
    <label for="update_user_data", value="Save my name and address for next time."></label>
  <% end %>
</div>

app/views/tools/_email_target_text.html.erb
To: <%= @actionPage.email_campaign.email_addresses %>
Subject: <%= @actionPage.email_campaign.subject %>

<%= @actionPage.email_campaign.message %>

app/views/tools/_loading.html.erb
<div class="progress progress-striped active" style="display:none;">
  <div class="progress-bar progress-bar-danger"  role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
    <span class="sr-only">
      Working
    </span>
  </div>
</div>

app/views/tools/_mailing_list.html.erb
<div class="tool mailing-list-tool">
  <div class="tool-container">
    <div class="tool-heading">
      <h2 class="tool-title">
        Join the mailing list
      </h2>
    </div>
    <div class="tool-body">
      <%= form_for :subscription, url: subscriptions_path, remote: true,
                    html: { id: "subscription-form", class: "", role: "form" } do |f| -%>
        <%= invisible_captcha %>
        <%= token_tag(form_authenticity_token) %>
        <%= f.hidden_field :mailing_list, value: "effector" -%>
        <fieldset>
          <%= f.email_field :email, id: :email, value: current_email,
                            class: "form-control", placeholder: "Email", "aria-label": "Email" -%>
        </fieldset>
        <%= f.submit "Subscribe", class: "eff-button", name: "commit" -%>
      <% end %>
    </div>
  </div>
</div>

app/views/tools/_petition_location.html.erb
<fieldset id='location' data-international-only="<%= params[:international_only] %>" <%= 'class=require' if @require_location -%>>
  <span class='intl-toggle'>
    <div class="row">
      <div>
        <%= f.text_field :zipcode, class: 'form-control',
          placeholder: "#{t(:zip_code)} #{@require_location ? '' : t(:optional)}",
          'aria-label': t(:zip_code),
          title: t('petition_errors.required.zip_code') -%>
      </div>

          <span class='intl-toggler pull-right hidden-if-no-js eff-button'><%= t :outside_the_us -%></span>

    </div>
  </span>

  <div class='intl-toggle intl collapse'>
      <%= f.text_field :city, placeholder: t(:city), 'aria-label': t(:city),
        class: 'form-control input-pair', pattern: '.*\S+.*', title: t('petition_errors.required.city')
      -%>
      <span class='intl-toggler pull-right hidden-if-no-js eff-button'><%= t :in_the_us -%></span>
      <%= f.select :country_code, Places.country_codes, { prompt: t(:country) },
        class: 'form-control' -%>
  </div>
</fieldset>

app/views/tools/_petition_success.html.erb
<p><strong>Success.</strong> Thanks for signing this petition!</p>
<% unless user_signed_in? -%>
  <% unless @user.new_record? -%>
    <p> You look familiar. If you sign in, we can help you fill out these forms
    faster. </p>
    <p> <%= link_to 'Sign in', new_user_session_path,
      class: 'login eff-button' -%> </p>
  <% else -%>
    <p> Want us to save your info for the next one? </p>
    <p> <%= link_to 'Register', new_user_registration_path,
      class: 'register eff-button' -%> </p>
  <% end -%>
<% end -%>

app/views/tools/_privacy_notice.html.erb
<h5 class="privacy-notice-header">
  <span class="customize-message-popover" data-toggle="tooltip" data-trigger="hover">?
    <span class="tooltiptext"><%= t :privacy_notice %></span>
 </span>
  How will EFF use this information?
</h5>

app/views/tools/_share.html.erb
<div class='vertical-share '>
  <b class='small'>Now help spread the word:</b>
  <a href='<%= twitter_share_url(@actionPage) -%>' class='twitter twitter-button'>
    <div class="sicon" id="stwit"></div>
    <div class="share-label">Share on Twitter</div>
  </a>
  <a href="<%= facebook_share_url(@actionPage) -%>" class="facebook facebook-button">
    <div class="sicon" id="sfb"></div>
    <div class="share-label">Share on Facebook</div>
  </a>

</div>
<p class="small donate">
  Have you <a href="https://supporters.eff.org/donate" target="blank">donated to EFF</a> lately?
  <% if !current_user %>
  <br />
  <strong><a href="/register">Sign up</a> for an EFF Action account and save your information for next time.</strong>
  <% end %>
</p>

app/views/tools/_thank_you.html.erb
<div class="thank-you tool-container">
  <div>
    <%= image_tag 'thankyou-circle.png', alt: 'Illustration of a woman with green hair using a laptop' %>
    <h3 class="tool-title thank-you-title">Thank You!</h3>
    <p>Your action is important and contributes
    to preserving a free, open internet.</p>
  </div>
  <div class="tool-body">
    <hr>
    <h5>Spread the word:</h5>
    <div class="share">
      <a data-network="twitter" href="<%= twitter_share_url(@actionPage) -%>" count="0" target="_blank" >
        <div class="sicon" id="stwit"></div>
      </a>
      <a href="<%= facebook_share_url(@actionPage) -%>" data-network="facebook" count="0" target="_blank"">
        <div class="sicon" id="sfb"></div>
      </a>
      <a href="<%= email_friends_url(@actionPage) -%>" count="0" target="_blank">
        <div class="sicon" id="semail"></div>
      </a>

      <div class="sicon copy-url-share" title="Show persistent url" id="slink"></div>
      <div class="url-field-share">
        <input type="text" readOnly />
      </div>
    </div>
  </div>
  <hr>
  <p> EFF is supported by donations from folks like you. We appreciate anything you can give! </p>
  <a class="eff-button" href="https://supporters.eff.org/donate" role="button" aria-pressed="false">Donate</a>
  <% if @actionPage.enable_tweet && @actionPage.tweet %>
    <% if @actionPage.tweet.targets.present? && (@actionPage.tweet.targets.size > 1) %>
    <div class="go-back">
      <button id="tweet-back">Want to tweet others? Go back</button>
    </div>
    <% end %>
  <% end %>
</div>

app/views/tools/_victory.html.erb
<div class="tool mailing-list-tool">
  <div class="tool-container">
    <div class="tool-heading">
      <h2 class="tool-title">
        We won!
      </h2>
    </div>
    <div class="tool-body">
      <% if @actionPage.enable_petition? %>
        <div class='victory-count'><b><%= @signature_count -%></b> signatures total</div>
      <% end %>
      <%= markdown @actionPage.victory_message %>
    </div>
  </div>
</div>

app/views/tools/email_target.html.erb
<div class='container'>
  <h2>Copy the following text:</h2>

  <textarea id='email_target_text'><%= render 'tools/email_target_text' %></textarea>
</div>