config/routes.rb
Actioncenter::Application.routes.draw do
  get "robots.txt", controller: :robots, action: :show, format: 'text'
  get "/heartbeat", to: "robots#heartbeat"

  # Root - Redundant - TODO - refactor
  get "welcome/index"
  root 'welcome#index'

  # EFF TOOLS (Call, Share, Petition) - External Reusable Services

  post "tools/call"
  post "tools/petition"
  post "tools/tweet"
  post "tools/email"
  post "tools/message-congress"
  get "tools/reps"
  get "tools/reps_raw"
  get "tools/social_buttons_count"

  get "smarty_streets/:action", controller: :smarty_streets
  get "petition/:id/recent_signatures", :to => "petition#recent_signatures", :format => 'json'

  # Handle notifications from Amazon SES
  post "bounce/:amazon_authorize_key", :to => "sns#bounce", :format => 'json'
  post "complaint/:amazon_authorize_key", :to => "sns#complaint", :format => 'json'

  get "ahoy/visit"

  # EFF Resources

  devise_for :users, path: '', path_names:  {sign_in:  'login',
                                             sign_out: 'logout',
                                             sign_up:  'register'},
                               controllers: {sessions: 'sessions', registrations: 'registrations'}

  devise_scope :user do
    get "/sessions/password_reset" => "sessions#password_reset"
  end

  resource :user, path: 'account', only: [:show, :edit, :update] do
    member do
      delete :clear_activity
    end
  end

  # override devise's user_root (defaults to site root)
  get 'account', to: 'users#show', as: 'user_root'

  resources :action_page, path: :action, only: [:index, :show] do
    member do
      get :embed_iframe
      get :signature_count
      get :filter
      get ':institution_id' => :show_by_institution, as: :institution
    end
    collection do
      get :embed
    end
  end

  resources :subscriptions, only: [:create, :edit]

  resources :partners, only: [:show, :edit, :update] do
    member do
      get :csv
      get :presentable_csv
      post 'users' => 'partners#add_user', as: :add_user
      delete 'users/:user_id' => 'partners#remove_user', as: :remove_user
    end
  end

  resources :congress_message_campaigns, only: :none do
    resources :congress_messages, only: [:new, :create], controller: :congress_messages
  end

  namespace :admin do

    resources :source_files, :only => [:index, :create, :destroy], :controller => 's3_uploads' do
      get :generate_key, :on => :collection
    end

    get 'mailer/:action/:id' => 'mailer#:action'

    resources :congress_message_campaigns, only: :none do
      member do
        get :date_tabulation
        get :congress_tabulation
        get "staffer_report/:bioguide_id", to: "congress_message_campaigns#staffer_report", as: :staffer_report
      end
    end

    resources :em
    resources :partners
    resources :topic_categories, :topic_sets, :topics

    resources :petitions, only: %i() do
      member do
        get :presentable_csv
        get :affiliation_csv
        delete "signatures" => "petitions#destroy_signatures", as: :signatures
      end
    end

    resources :action_pages do
      get :publish
      get :unpublish
      get :destroy
      post 'update_featured_pages', :on => :collection
      patch :preview
      get :duplicate
      get :status
      get :edit_partners

      get :events
      get :"events-table"
      get :views, to: "events#views"

      resources :petitions, only: :show

      collection do
        get :homepage
        post :homepage, to: "action_pages#update_featured_action_pages"
      end
    end

    resources :institutions, except: [:show] do
      get :upload, on: :collection
      post :import, on: :collection
    end

    resources :users, only: [:index, :update]

    get "images", to: "images#index"

    resources :events, only: [:index]

    resources :categories, only: [:index, :create, :destroy]
  end
end

app/models/action_page.rb
class ActionPage < ActiveRecord::Base
  extend FriendlyId, AmazonCredentials

  include PgSearch
  pg_search_scope :search,
                  against: [
                    :title,
                    :slug,
                    :summary,
                    :description,
                    :email_text,
                  ],
                  associated_against: {
                    call_campaign: [:title, :message],
                    congress_message_campaign: [:subject, :message, :campaign_tag],
                    email_campaign: [:subject, :message],
                    petition: [:title, :description],
                    tweet: [:target, :message, :cta]
                  },
                  using: { tsearch: { prefix: true } }

  friendly_id :title, use: [:slugged, :history]
  scope :published, -> { where(published: true) }

  has_many :events, class_name: Ahoy::Event
  has_many :partnerships
  has_many :partners, through: :partnerships
  has_many :action_institutions
  has_many :institutions, through: :action_institutions
  has_many :affiliation_types

  belongs_to :petition
  belongs_to :tweet
  belongs_to :email_campaign
  belongs_to :congress_message_campaign
  belongs_to :call_campaign
  belongs_to :category, optional: true
  belongs_to :active_action_page_for_redirect, class_name: "ActionPage",
             foreign_key: "archived_redirect_action_page_id"
  belongs_to :author, class_name: "User", foreign_key: :user_id, optional: true

  accepts_nested_attributes_for :tweet, :petition, :email_campaign,
    :call_campaign, :congress_message_campaign, :affiliation_types, :partnerships,
    reject_if: :all_blank

  has_attached_file :featured_image, amazon_credentials.merge(default_url: "missing.png")
  has_attached_file :background_image, amazon_credentials
  has_attached_file :og_image, amazon_credentials
  validates_media_type_spoof_detection :featured_image,
    if: -> { featured_image.present? && featured_image_file_name_came_from_user? }
  validates_media_type_spoof_detection :background_image,
    if: -> { background_image.present? && background_image_file_name_came_from_user? }
  validates_media_type_spoof_detection :og_image,
    if: -> { og_image.present? && og_image_file_name_came_from_user? }
  do_not_validate_attachment_file_type [:featured_image, :background_image, :og_image]

  #validates_length_of :og_title, maximum: 65
  after_save :no_drafts_on_homepage
  after_save :set_congress_tag, if: -> { enable_congress_message }

  scope :categorized, ->(category) { joins(:category).where(categories: { title: category }) }

  def self.type(*types)
    scopes = Array(types).flatten.map do |t|
      unless %w(call congress_message email petition tweet redirect).include?(t)
        raise ArgumentError, "unrecognized type #{t}"
      end

      where(:"enable_#{t}" => true)
    end

    scopes.inject(:or) || all
  end

  def action_type
    %w(call congress_message email petition tweet redirect).each do |type|
      return type.titleize if self[:"enable_#{type}"]
    end

    nil
  end

  def self.status(status)
    unless %w(archived victory live draft).include?(status)
      raise ArgumentError, "unrecognized status #{status}"
    end
    case status
    when "live"
      where(published: true, archived: false, victory: false)
    when "draft"
      where(published: false, archived: false, victory: false)
    else
      where(status => true)
    end
  end

  def mailing_list_partners
    partnerships.where(enable_mailings: true).partners
  end

  def should_generate_new_friendly_id?
    # create slugs with FriendlyId and respect our custom slugs
    # set a custom slug with `page.update(slug: new_slug)`
    title.present? && (slug.blank? || title_changed?)
  end

  def call_tool_title
    call_campaign &&
      call_campaign.title.length > 0 &&
      call_campaign.title ||
      "Call Your Legislators"
  end

  def message_rendered
    # TODO: just write a test for this and rename this to .to_md
    call_campaign && call_campaign.message || ""
  end

  def verb
    return "sign" if enable_petition?
    return "tweet" if enable_tweet?
  end

  def tweet_individual?
    tweet && tweet.target.present?
  end

  def tweet_congress?
    tweet && tweet.target.blank?
  end

  def redirect_from_archived_to_active_action?
    archived? && active_action_page_for_redirect && !victory?
  end

  def template
    self[:template] || :show
  end

  def layout
    self[:layout] || :default
  end

  def og_title
    self[:og_title].presence || title
  end

  def image
    [og_image, background_image, featured_image].find(&:present?)
  end

  def actions_taken_percent
    return 0 if view_count == 0
    @percent ||= (action_count / view_count.to_f) * 100
  end

  def status
    if archived?
      "archived"
    elsif victory?
      "victory"
    elsif published?
      "live"
    else
      "draft"
    end
  end

  def status=(status)
    case status
    when "live"
      self.published = true
      self.archived = false
      self.victory = false

    when "archived"
      self.published = false
      self.archived = true
      self.victory = false

    when "victory"
      self.published = true
      self.archived = false
      self.victory = true

    when "draft"
      self.published = false
      self.archived = false
      self.victory = false
    end
  end

  def no_drafts_on_homepage
    FeaturedActionPage.where(action_page_id: id).destroy_all unless published?
  end

  def set_congress_tag
    return unless congress_message_campaign.campaign_tag.blank?
    congress_message_campaign.update(campaign_tag: slug)
  end
end

app/controllers/action_page_controller.rb
class ActionPageController < ApplicationController
  include ActionPageDisplay

  before_action :set_action_page,
                :protect_unpublished,
                :redirect_to_specified_url,
                :redirect_from_archived_to_active_action,
                only: [:show, :show_by_institution, :embed_iframe,
                       :signature_count, :filter]
  before_action :redirect_to_cannonical_slug, only: [:show]
  before_action :set_institution, only: [:show_by_institution, :filter]
  before_action :set_action_display_variables, only: [:show,
                                                      :show_by_institution,
                                                      :embed_iframe,
                                                      :signature_count,
                                                      :filter]

  skip_before_action :verify_authenticity_token, only: :embed

  after_action :allow_iframe, only: :embed_iframe

  manifest :action_page

  def show
    render @actionPage.template, layout: @actionPage.layout
  end

  def index
    @actionPages = ActionPage.where(published: true, archived: false, victory: false).
      paginate(page: params[:page], per_page: 9).
      order(created_at: :desc)

    @actionPages = @actionPages.categorized(params[:category]) if params[:category].present?

    respond_to do |format|
      format.html
      format.atom
      format.json
    end
  end

  def embed
    render "action_page/embed.js.erb", layout: false
  end

  def embed_iframe
    @css = params[:css] if params.include? :css
    render layout: "application-blank"
  end

  def signature_count
    @actionPage = ActionPage.friendly.find(params[:id])

    if petition = @actionPage.petition
      render text: petition.signatures.count
    else
      render text: "0"
    end
  end

  def show_by_institution
    render @actionPage.template, layout: @actionPage.layout
  end

  def filter
    redirect_to institution_action_page_url(params[:id], @institution)
  end

  private

  def set_action_page
    @actionPage = ActionPage.friendly.find(params[:id].strip)
  end

  def protect_unpublished
    unless @actionPage.published?
      if current_user.try(:admin?) || current_user.try(:collaborator?)
        flash.now[:notice] = "This page is not published. Only Admins and Collaborators can view it."
      else
        raise ActiveRecord::RecordNotFound
      end
    end
  end

  def redirect_to_specified_url
    if @actionPage.enable_redirect
      redirect_to @actionPage.redirect_url, status: 301
    end
  end

  def redirect_from_archived_to_active_action
    if @actionPage.redirect_from_archived_to_active_action?
      # Users can access actions they've taken in the past as a historical record
      unless current_user and (current_user.taken_action? @actionPage or current_user.admin?)
        redirect_to @actionPage.active_action_page_for_redirect
      end
    end
  end

  def redirect_to_cannonical_slug
    redirect_to(@actionPage) unless request.path == action_page_path(@actionPage)
  end

  def set_institution
    @institution = Institution.friendly.find(params[:institution_id])
  end

  def allow_iframe
    response.headers.except! "X-Frame-Options"
  end
end

app/helpers/action_page_helper.rb
module ActionPageHelper
  def twitter_share_url(action_page)
    message = [
      action_page.share_message, action_page_url(action_page)
    ].map(&:presence).compact.join(" ")

    suffix = if Rails.application.config.twitter_handle
               " via @#{Rails.application.config.twitter_handle}"
             end
    message += suffix if action_page.share_message.to_s.length + suffix.length <= 117

    related = Rails.application.config.twitter_related.to_a.join(",")

    "https://twitter.com/intent/tweet?text=#{u message}&related=#{related}"
  end


  def tweet_url(target, message)
    message = [target, message].compact.join(" ")
    related = Rails.application.config.twitter_related.to_a.join(",")
    "https://twitter.com/intent/tweet?text=.#{u message}&related=#{related}"
  end

  def facebook_share_url(action_page)
    "https://www.facebook.com/sharer/sharer.php?" + {
      u: action_page_url(action_page),
      display: "popup"
    }.to_param
  end

  def email_friends_url(action_page)
    subject = t("email_friends.subject")
    message = t("email_friends.message", title: action_page.title, url: action_page_url(action_page))

    "mailto:?subject=#{u subject}&body=#{u message}"
  end

  def rep_photo_src(bioguide_id)
    asset_path "congress-images-102x125/i/#{bioguide_id}.jpg"
  end

  def rep_tweet_link(rep)
    tweet_link("@#{rep.twitter_id}", class: "btn-tweet rep")
  end

  def individual_tweet_link(tweet_target)
    tweet_link(tweet_target.twitter_id, class: :individual)
  end

  def tweet_link(twitter_id, params = {})
    twitter_id = "@#{twitter_id}" unless twitter_id.to_s.starts_with? "@"
    link_to raw("<i class='icon-twitter-1'></i> Tweet #{twitter_id}"), # rubocop:disable Rails/OutputSafety
            tweet_url(twitter_id, @tweet.try(:message)),
            class: "btn btn-tweet btn-default #{params[:class]}",
            data: { twitter_id: twitter_id },
            target: :blank
  end

  def tweet_tool_classes
    classes = []
    classes << "house" if @actionPage.tweet.target_house?
    classes << "senate" if @actionPage.tweet.target_senate?
    classes.join(" ")
  end

  def parse_email_text(options = {})
    email_text = @actionPage.email_text

    url = action_page_url(@actionPage)
    title = @actionPage.title
    name = html_escape(options[:name])

    email_text.
      gsub(/\$TITLE/, title).
      gsub(/\$URL/, url).
      gsub(/\$NAME/, name)
  end

  def visible_partners
    mailings_enabled = @actionPage.partners.includes(:partnerships)
                                  .where(partnerships: { enable_mailings: true })
    return mailings_enabled if params[:partner].blank?
    mailings_enabled.where(code: params[:partner])
  end
end

app/helpers/admin/action_pages_helper.rb
module Admin
  module ActionPagesHelper
    def call_campaign_options_for_select
      if CallTool.enabled?
        CallTool.campaigns.map do |campaign|
          ["#{campaign['name']} (#{campaign['status']})", campaign["id"]]
        end.sort_by(&:last).reverse
      else
        []
      end
    rescue SystemCallError, RestClient::Exception
      []
    end

    def congress_member_options_for_select(campaign)
      selected = (campaign.target_bioguide_ids || "").split(/\s*,\s*/)

      state_names = Places.us_state_codes.invert

      congressional_bioguides = []
      grouped_reps = CongressMember.all.group_by do |rep|
        congressional_bioguides << rep.bioguide_id
        state_names[rep.state]
      end

      grouped_reps.each do |state, state_reps|
        grouped_reps[state] = state_reps.sort_by(&:last_name).map do |rep|
          label = "#{rep.full_name} (#{rep.bioguide_id})"
          [label, rep.bioguide_id]
        end
      end

      grouped_reps = grouped_reps.keys.sort.map { |k| [k, grouped_reps[k]] }

      non_congressional_bioguides = []
      CongressMessageCampaign.targets_bioguide_ids.pluck(:target_bioguide_ids).each do |targets|
        non_congressional_bioguides.concat(targets.split(/\s*,\s*/) - congressional_bioguides)
      end

      if non_congressional_bioguides.present?
        grouped_reps.unshift(["Non-congressional", non_congressional_bioguides.sort])
      end

      grouped_options_for_select(grouped_reps, selected)
    end
  end
end

app/views/action_page/_letter.html.erb
<div class='letter' id="letter">
  <div class='body'>
    <div class='date'><%= I18n.l Time.now, format: "%B %-d, %Y" %></div>
    <% if defined? description -%>
      <div class='description'><%= markdown description %></div>
    <% elsif @actionPage.petition.description -%>
      <div class='title'><strong><%= @actionPage.petition.title -%></strong></div>
      <div class='description'><%= markdown @actionPage.petition.description -%></div>
    <% end -%>
    <div class='signed'><%= I18n.t :signed  %></div>
    <div class='close'>
      <div class='name'><%= I18n.t :your_name %></div>
    </div>
  </div>
</div>

app/views/action_page/_meta_tags.html.erb
<% summary = strip_tags stripdown(@actionPage.summary) -%>
<%
    image_url = if @actionPage.image.try(:exists?)
                  image_url(@actionPage.image.to_s)
                else
                  image_url("og-image-default.png")
                end
-%>

<meta name='description' content='<%= summary -%>'>
<meta property='og:type' content='article'>
<meta property='og:url' content='<%= action_page_url(@actionPage) -%>'>
<meta property='og:title' content='<%= @actionPage.og_title -%>'>
<meta property='og:description' content='<%= summary -%>'>
<meta property='og:image' content='<%= asset_path(image_url) -%>'>
<meta property='og:image:secure_url' content='<%= asset_path(image_url) -%>'>
<% if fb = Rails.application.config.facebook_handle %>
  <meta property='article:publisher' content='https://www.facebook.com/<%= fb -%>'>
<% end %>

<meta name='twitter:card' content='summary_large_image'>
<meta name='twitter:site' content='<%= twitter_handle -%>'>
<meta name='twitter:creator' content='<%= twitter_handle -%>'>
<meta name='twitter:image:src' content='<%= asset_path(image_url) -%>'>
<meta name='twitter:title' content='<%= @actionPage.og_title -%>'>
<meta name='twitter:description' content='<%= summary -%>'>

app/views/action_page/_partner_logos.html.erb
<% if @actionPage.partners.present? && @actionPage.partners.any? { |p| p.logo.present? } %>
  <h2 class="partners-title">Who We Are</h2>
  <div class="partner-logos">
  <%= image_tag "EFF_Monogram-red" %>
    <% @actionPage.partners.each do |partner| %>
      <%= image_tag partner.logo if partner.logo.present? %>
    <% end %>
  </div>
<% end %>

app/views/action_page/_reps.html.erb
<% @reps.each do |rep| -%>
  <div class='rep <%= rep.chamber -%>'>
    <img src="<%= rep_photo_src(rep.bioguide_id) -%>" class='rep'>
    <%= rep_tweet_link(rep) -%>
  </div>
<% end -%>

app/views/action_page/embed.js.erb
/*!
  * domready (c) Dustin Diaz 2014 - License MIT
  */
!function (name, definition) {

  if (typeof module != 'undefined') module.exports = definition()
  else if (typeof define == 'function' && typeof define.amd == 'object') define(definition)
  else this[name] = definition()

}('domready', function () {

  var fns = [], listener
    , doc = document
    , hack = doc.documentElement.doScroll
    , domContentLoaded = 'DOMContentLoaded'
    , loaded = (hack ? /^loaded|^c/ : /^loaded|^i|^c/).test(doc.readyState)


  if (!loaded)
  doc.addEventListener(domContentLoaded, listener = function () {
    doc.removeEventListener(domContentLoaded, listener)
    loaded = 1
    while (listener = fns.shift()) listener()
  })

  return function (fn) {
    loaded ? fn() : fns.push(fn)
  }

});

/*!
  * EFF Action Center include iframe
  * AGPLv3
  */
(function() {
  function embed(widget) {
    var width = 500;
    var iframe_tag = document.createElement("iframe");

    window.addEventListener("message", function(event) {
      if (event.origin == "<%= (request.ssl? ? "https://" : "http://") + request.env['HTTP_HOST'] %>") {
        var window_height = event.data;
        iframe_tag.height = window_height + "px";
      }
    }, false);


    var embed_url = widget.getAttribute("href").split('?', 2);
    embed_url = embed_url[0] + '/embed_iframe?' + (embed_url[1] || '');

    if (typeof ac_embed !== "undefined"){
      if("width" in ac_embed)
        width = ac_embed.width;

      if("css" in ac_embed)
        embed_url += "&css=" + encodeURIComponent(ac_embed.css);

      if("no_css" in ac_embed && ac_embed.no_css == true)
        embed_url += "&no_css=true";

      if("css_content" in ac_embed) {
        var css_content = document.querySelector(ac_embed.css_content).innerHTML;
        embed_url += "&css_content=" + escape(css_content);
      }

      if("button_text" in ac_embed)
        embed_url += "&button_text=" + encodeURIComponent(ac_embed.button_text);

      if("international_only" in ac_embed && ac_embed.international_only == true)
        embed_url += "&international_only=true";

      if ("non_us_option" in ac_embed && ac_embed.non_us_option == "petition")
        embed_url += "&non_us_option=petition";

      if ("location" in ac_embed)
        embed_url += "&" + hash_params(ac_embed.location)

      if ("bioguide_ids" in ac_embed)
        embed_url += array_params("bioguide_ids", ac_embed.bioguide_ids)
    }

    iframe_tag.setAttribute("src", embed_url);
    iframe_tag.setAttribute("frameborder", 0);
    iframe_tag.setAttribute("width", width);

    widget.parentNode.insertBefore(iframe_tag, widget);
    widget.remove();
  }

  function array_params(key, array) {
    return array.map(x => "&" + key + "[]=" + encodeURIComponent(x))
                .join("");
  }

  function hash_params(obj) {
    var str = "";
    for (var key in obj) {
      if (str != "") {
        str += "&";
      }
      str += key + "=" + encodeURIComponent(obj[key]);
    }
    return str;
  }

  domready(function(){
    var widgets = document.querySelectorAll("#action-center-widget, .action-center-widget")

    for (var i=0; i < widgets.length; ++i)
      embed(widgets[i]);
  });
})();

app/views/action_page/embed_iframe.html.erb
<% content_for :head do %>
  <% if @css %>
    <%= stylesheet_link_tag @css, media: "all" %>
    <%= stylesheet_link_tag 'embed', media: "all" %>
  <% end %>
  <% if params.include? "css_content" %>
    <style>
      <%= params["css_content"] %>
    </style>
  <% end %>
<% end -%>
<%= render "tools/container" %>
<%= ahoy_track_tag("embedded_view", @actionPage.id) %>

app/views/action_page/index.html.erb
<div class="top-section">
  <div class="container" role="main">
    <h1><%= t :organization_abbreviation -%> Campaigns</h1>
  </div>
</div>

<section class="more-actions">
  <%= form_tag action_page_index_path, method: :get, id: "action-page-filter" do %>
    <%= select_tag :category,
      options_from_collection_for_select(Category.all.order(:title).uniq,
                                         :title, :title, params[:category]),
      include_blank: "All campaigns" %>
  <% end %>
  <div class='container'>
    <% @actionPages.each_slice(3) do |array_of_3_actions| %>
      <div class="row">
        <% array_of_3_actions.each do |actionPage|%>
            <div>
              <%= link_to action_page_path(actionPage) do%>
                <div class="image">
                  <%= image_tag(actionPage.featured_image) %>
                </div>
              <% end %>

              <% if actionPage.category.present? %>
                <h5 class="category">
                  <%= actionPage.category.title %>
                </h5>
              <% end %>

              <div class="text">
                <h3>
                <%= link_to action_page_path(actionPage) do%>
                  <%= actionPage.title -%>
                <% end %>
                </h3>
              </div>
            </div>
        <% end %>
      </div>
    <% end %>
    <%= will_paginate @actionPages %>
  </div>
</section>

app/views/action_page/show.html.erb
<% content_for :head do -%>
<%= render 'action_page/meta_tags' -%>

<% end -%>
<div class="top-section">
  <div class="container" role="main">
    <div class="row">
      <div class='short-description'>
        <% if @actionPage.category.present? %>
          <h5 class="category"><%= @actionPage.category.title -%></h5>
        <% end %>
        <h1><%= @actionPage.title -%></h1>
        <%= image_tag(@actionPage.featured_image) %>
        <%= markdown @actionPage.summary -%>

        <%= render "action_page/partner_logos" %>

        <% if @actionPage.enable_petition? && @petition && @petition.description.present? && !@actionPage.description.include?('``` letter') -%>
          <%= render(partial: "action_page/letter", layout: false) %>
        <% end -%>

        <% if @actionPage.description.present? %>
          <input type='checkbox' style='display: none' id="learn-more">
          <label for="learn-more">Learn More</label>
          <div class="description" id="description">
            <% if @related_content.found? %>
            <div class="related-content">
              <h4>Related Content</h4>
              <%= link_to @actionPage.related_content_url do %>
                <div class="image">
                  <%= image_tag(@related_content.image) %>
                </div>
                <h5><%= @related_content.title %></h5>
              <% end %>
            </div>
              <div class="desc-text">
                <p><%= markdown @actionPage.description -%></p>
              </div>
              <div class="related-content mobile">
                <h4>Related Content</h4>
                <%= link_to @actionPage.related_content_url do %>
                  <div class="image">
                    <%= image_tag(@related_content.image) %>
                  </div>
                  <h5><%= @related_content.title %></h5>
                <% end %>
              </div>
            <% else %>
              <div class="desc-text full">
                <p><%= markdown @actionPage.description -%></p>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class=" action-content" id="action-content" data-action-id="<%= @actionPage.id -%>" >
        <%= render "tools/container" %>
        <% if @actionPage.petition && @actionPage.enable_petition? && @actionPage.petition.enable_affiliations? -%>
        <%= render(partial: "tools/affiliation_signatures", layout: false) %>
        <% end -%>
      </div>
    </div>
  </div>
</div>
<%= ahoy_track_tag("show", @actionPage.id) %>