config/routes.rb
Actioncenter::Application.routes.draw do
  get "robots.txt", controller: :robots, action: :show, format: 'text'
  get "/heartbeat", to: "robots#heartbeat"

  # Root - Redundant - TODO - refactor
  get "welcome/index"
  root 'welcome#index'

  # EFF TOOLS (Call, Share, Petition) - External Reusable Services

  post "tools/call"
  post "tools/petition"
  post "tools/tweet"
  post "tools/email"
  post "tools/message-congress"
  get "tools/reps"
  get "tools/reps_raw"
  get "tools/social_buttons_count"

  get "smarty_streets/:action", controller: :smarty_streets
  get "petition/:id/recent_signatures", :to => "petition#recent_signatures", :format => 'json'

  # Handle notifications from Amazon SES
  post "bounce/:amazon_authorize_key", :to => "sns#bounce", :format => 'json'
  post "complaint/:amazon_authorize_key", :to => "sns#complaint", :format => 'json'

  get "ahoy/visit"

  # EFF Resources

  devise_for :users, path: '', path_names:  {sign_in:  'login',
                                             sign_out: 'logout',
                                             sign_up:  'register'},
                               controllers: {sessions: 'sessions', registrations: 'registrations'}

  devise_scope :user do
    get "/sessions/password_reset" => "sessions#password_reset"
  end

  resource :user, path: 'account', only: [:show, :edit, :update] do
    member do
      delete :clear_activity
    end
  end

  # override devise's user_root (defaults to site root)
  get 'account', to: 'users#show', as: 'user_root'

  resources :action_page, path: :action, only: [:index, :show] do
    member do
      get :embed_iframe
      get :signature_count
      get :filter
      get ':institution_id' => :show_by_institution, as: :institution
    end
    collection do
      get :embed
    end
  end

  resources :subscriptions, only: [:create, :edit]

  resources :partners, only: [:show, :edit, :update] do
    member do
      get :csv
      get :presentable_csv
      post 'users' => 'partners#add_user', as: :add_user
      delete 'users/:user_id' => 'partners#remove_user', as: :remove_user
    end
  end

  resources :congress_message_campaigns, only: :none do
    resources :congress_messages, only: [:new, :create], controller: :congress_messages
  end

  namespace :admin do

    resources :source_files, :only => [:index, :create, :destroy], :controller => 's3_uploads' do
      get :generate_key, :on => :collection
    end

    get 'mailer/:action/:id' => 'mailer#:action'

    resources :congress_message_campaigns, only: :none do
      member do
        get :date_tabulation
        get :congress_tabulation
        get "staffer_report/:bioguide_id", to: "congress_message_campaigns#staffer_report", as: :staffer_report
      end
    end

    resources :em
    resources :partners
    resources :topic_categories, :topic_sets, :topics

    resources :petitions, only: %i() do
      member do
        get :presentable_csv
        get :affiliation_csv
        delete "signatures" => "petitions#destroy_signatures", as: :signatures
      end
    end

    resources :action_pages do
      get :publish
      get :unpublish
      get :destroy
      post 'update_featured_pages', :on => :collection
      patch :preview
      get :duplicate
      get :status
      get :edit_partners

      get :events
      get :"events-table"
      get :views, to: "events#views"

      resources :petitions, only: :show

      collection do
        get :homepage
        post :homepage, to: "action_pages#update_featured_action_pages"
      end
    end

    resources :institutions, except: [:show] do
      get :upload, on: :collection
      post :import, on: :collection
    end

    resources :users, only: [:index, :update]

    get "images", to: "images#index"

    resources :events, only: [:index]

    resources :categories, only: [:index, :create, :destroy]
  end
end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user
    belongs_to :action_page
    counter_culture :action_page, column_name: proc { |record|
      if record.name == "Action"
        "action_count"
      elsif record.name == "View"
        "view_count"
      else
        nil
      end
    }

    scope :actions,    -> { where(name: "Action") }
    scope :views,      -> { where(name: "View") }
    scope :emails,     -> { where("properties ->> 'actionType' = 'email'") }
    scope :congress_messages, -> { where("properties ->> 'actionType' = 'congress_message'") }
    scope :calls,      -> { where("properties ->> 'actionType' = 'call'") }
    scope :signatures, -> { where("properties ->> 'actionType' = 'signature'") }
    scope :tweets,     -> { where("properties ->> 'actionType' = 'tweet'") }
    scope :on_page,    -> (id) { where(action_page_id: id) }
    scope :in_range, ->(start_date, end_date) {
      where(time: start_date..end_date.tomorrow)
    }

    before_save :user_opt_out
    before_save :anonymize_views
    after_create :record_civicrm

    TYPES = %i(views emails tweets calls signatures congress_messages).freeze

    def self.action_types(action_page = nil)
      TYPES.dup.tap do |t|
        if action_page.present?
          t.delete(:calls) if !action_page.enable_call
          t.delete(:congress_messages) if !action_page.enable_congress_message
          t.delete(:emails) if !action_page.enable_email
          t.delete(:signatures) if !action_page.enable_petition
          t.delete(:tweets) if !action_page.enable_tweet
        end
      end
    end

    # Formats the event data for a chart
    def self.chart_data(type: nil, range: nil)
      by_type = TYPES.include? type.try(:to_sym)
      collection = by_type ? all.send(type) : group(:name)
      collection.group_by_day(
        :time,
        format: "%b %-e %Y",
        range: range,
        default_value: 0
      ).count
    end

    # Reformats chart data for use in tables
    # Returns the following format:
    # {
    #   "June 1 2019": {
    #     action: 10,
    #     view: 20
    #   },
    #   ...
    # }
    def self.table_data
      {}.tap do |table|
        chart_data.each do |(type, date), count|
          table[date] ||= {}
          key = type.downcase.to_sym
          table[date][key] = count
        end
      end
    end

    # Returns events grouped by date. Can be used to chart event collections
    # with only one event type
    def self.group_by_date
      group_by_day
    end

    def self.summary
      { view: views.count, action: actions.count }
    end

    def user_opt_out
      if user
         user_id = nil unless user.record_activity?
      end
    end

    def record_civicrm
      if name == "Action" && user && action_page_id
        user.add_civicrm_activity! action_page_id
      end
    end

    def anonymize_views
      self.user_id = nil if name == "View"
    end
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  include DateRange
  before_action :set_dates

  def index
    @events = Ahoy::Event.all.in_range(@start_date, @end_date)
    respond_to do |format|
      format.html { @summary = @events.summary }
      format.json {
        render json: @events.chart_data(
                 type: params[:type],
                 range: @start_date..@end_date
               )
      }
    end
  end
end

app/views/admin/events/_sidebar.html.erb
<div id="analytics-nav">
  <% if action_page.present? %>
    <%= link_to "Chart", admin_action_page_events_path(action_page),
      class: "btn sm #{"active" if active == :chart }" %>
    <%= link_to "Table", admin_action_page_events_table_path(action_page),
      class: "btn sm #{"active" if active == :table }" %>
  <% end %>
  <div class="analytics-filters">
    <h3>Filters</h3>
    <%= form_tag path, method: :get, id: "analytics-filters-form" do %>
      <div class="form-item">
        <%= label_tag "Date Range" %>
        <input type="text" id="date_range" name="date_range_text" value="<%= date_range_string %>" />
      </div>

      <div class="form-actions">
        <button type="reset" class="btn btn-default btn-sm">Clear filters</button>
      </div>
    <% end %>
    <h3>Summary</h3>
    <p>Views: <%= summary[:view] %></p>
    <p>Actions Taken: <%= summary[:action] %></p>
    <p><%= percentage(summary[:action], summary[:view]) %> of views led to actions</p>
  </div>
  <div>
  </div>
</div>

app/views/admin/events/index.html.erb
<% content_for(:nav) { render "admin/nav" } %>

<%= render 'sidebar', path: admin_events_path, action_page: nil, summary: @summary %>

<div class="charts">
  <% Ahoy::Event.action_types.each do |type| %>
    <h3><%= t(type, scope: :ahoy) %></h3>
    <%= line_chart(admin_events_path(type: type, date_range_text: date_range_string),
                   height: "200px", discrete: true) %>
  <% end %>
</div>

app/views/admin/events/table.html.erb
<div class="container">
  <h3>Action page analytics for: <em><%= @actionPage.title %></em></h3>
  <table class="table table-striped" >
    <col>
    <% @columns.each do |_| %>
      <colgroup span="2">
    <% end %>
    <thead>
      <tr>
        <td></td>
        <% @columns.each do |c| %>
          <th colspan="2">
            <%= t(c, scope: :ahoy) %>
          </th>
        <% end %>
        <% if @fills.present? %>
          <th colspan="2">Congress Messages Submitted</th>
        <% end %>
      </tr>
      <tr>
        <th>Date</th>
        <% @columns.each do |_| %>
          <th class="subheader">Daily</th>
          <th class="subheader">Total</th>
        <% end %>
        <% if @fills.present? %>
          <th class="subheader">Daily</th>
          <th class="subheader">Total</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @totals = Hash.new(0) %>
      <% @data.each do |date, counts| %>
        <tr>
          <td><%= date.to_datetime.strftime("%B %-d, %Y") %></td>
          <% @columns.each do |c| %>
            <td><%= counts[c] || 0 %></td>
            <td><%= @totals[c] += counts[c] || 0 %></td>
          <% end %>
          <% if @fills.present? %>
            <td><%= @fills[date] || 0 %></td>
            <td><%= @totals[:fills] += @fills[date] || 0 %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>